server:
    port: 8080

spring:
    datasource:
        url: jdbc:oracle:thin:@192.168.0.152:1521/orcl
        username: TJEPPV5
        password: citms
        driver-class-name: oracle.jdbc.driver.OracleDriver


mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.springboottest1.entity
